### ISSUE TITLE
Oct. 16

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/lemur#4]
| Person | Task | DoD | Links/Status |
| --------- | ------ | ------- | ---------------- |
| @rmarren1 | Multivariate Time Series Distance Functions | Explore prior work on defining similarity / distance functions on multivariate time series ([one](http://science.sciencemag.org/content/344/6182/386.full), [oneandahalf](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.106.7999&rep=rep1&type=pdf), [two](http://www.sciencedirect.com/science/article/pii/S0031320305001305), [three](http://www.sciencedirect.com/science/article/pii/S1053811998903913#!), [four](https://link.springer.com/article/10.1007%2FPL00007990?LI=true), [five](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.99.204101), [six](https://link.springer.com/article/10.1007%2Fs001840000055?LI=true), [seven](http://ieeexplore.ieee.org/abstract/document/1443353/), [eight](https://link.springer.com/content/pdf/10.1007/b136725.pdf#page=537)), algorithms.md for one (chosen by which one is the most simple and has a statistical setting closest to our data) using resting state and naturalistic viewing eeg as real data to test (e.g. for one subject, split their resting state scan into 10 equal parts, their naturalistic viewing scan into 10 equal parts, and compute a distance matrix using the algorithm, with rows and columns grouped by resting/naturalistic). | In progress |
| @nkumarcc | Clustering of pairwise distance matricies | (Dendogram in R, ) Implementation of one visualization method and one analysis method. Visualization method is either a heatmap, a graph with colorized / weighted edges, ect.  Clustering is one of ([multidimensional scaling](https://en.wikipedia.org/wiki/Multidimensional_scaling), [heirarchical clustering](https://en.wikipedia.org/wiki/Hierarchical_clustering), [SPIN (sorting points into neighborhoods)](https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/bti329), [diffusion maps](http://www.pnas.org/content/102/21/7432.full), [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN)) | In Progress |
| @YukaLiu0707 | Explore dimensional theories of mental health (seeing whether we can do something similar to the p-factor paper with our data) | [DoD](https://github.com/NeuroDataDesign/lemur-f17s18/blob/master/docs/YukaLiu0707/DoDs/Week%2010-16.ipynb) | In Progress |
| @vidurkailash | Generalized distance matrix computation, visualization | Create a general function that takes as input 1. a list of N objects 2. an (optional) list of N labels 3. a distance function that takes as input two objects and outputs a number 4. a flag as to whether or not the distance function is symmetric, add to the API, this function should be parallelized to maximize the core availability. Create a visualization function that takes as input a similarity matrix and outputs a heatmap, with labels and a red-to-blue color scale. | In Progress | 
| @rmehta004 | Scripts to convert dataset to nice format, upload to S3 | Scripts to 1. Download k subjects from the HBNB S3 bucket 2. Reformat the data to be in the [BIDS-EEG](http://bids.neuroimaging.io/) format (include both raw data, and preprocessed data from HBNB) 3. Upload the data back to our own S3 bucket. For now, do this for n=5 subjects. These data will be used for automated testing of our visualization routines and to begin to build a pipeline. DoD will be showing a screenshot of these data in our S3 bucket, and .md summary of what the data format looks like (descriptive folder structure) | in progress |

**Comment by ebridge2** [comment]
@rmarren1 do you plan on doing anything with the distance matrix once computed under a given metric? Ie, cluster, classify, etc?

@nkumarcc can you propose any simulations you think might be relevant for the algorithm method chosen when you get there?

@YukaLiu0707 can you think of a basic simulation setting you could use the p-factor paper for?

@vidurkailash :+1:

@rmehta004 :+1:

**Comment by ebridge2** [comment]
good work guys; much better!

**Comment by rmarren1** [comment]
Was planning on ordering rows and columns by labels (gender, age, ect) to see if there is some sort of structure that can be measured by different metrics
